export { IconDiscord } from './icon-discord'
export { IconGithub } from './icon-github'
export { IconLinuxDo } from './icon-linuxdo'
export { IconTelegram } from './icon-telegram'
export { IconWeChat } from './icon-wechat'
